version: "3.7"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - CREDENTIALS_URL=http://localhost:8002/users/credentials
      - CREDENTIALS_API_KEY=iwhdiodhoiwehwioh
      - SECRET_JWT_KEY=71e44ea7cc314cf222fcee8403743c5b4056ebc1c9d82b0c95c0c5fc17de89c1
      - TOKEN_EXPIRATION_MINUTES=30
      - ACCESS_TOKEN_KEY=token
      - USERNAME_RETURN_KEY=username
      - ID_RETURN_KEY=id
    network_mode: host
